### ISSUE TITLE
If switch to php7 then apache not start

### ISSUE THREAD

**Issue by krausv** [JanTvrdik/PhpVersionSwitcher#21]
Hi,
i have a problem with switching on php 7 (7.0.2).
![bez nazvu](https://cloud.githubusercontent.com/assets/5638224/12481952/ed2ec1a6-c04c-11e5-9e41-703da5175d64.png)

If I switch php version and start apache from cmd, so apache works correctly. Error log is clean.

If I restart PhpVersionSwitcher and start apache then apache works fine. This problem is only on php7.
Older versions of php works fine (5.6, 5.5, 5.4)

Do you have any solution, please?

Thanks

**Comment by JanTvrdik** [comment]
Have you read the 3rd point of https://github.com/JanTvrdik/PhpVersionSwitcher#apache--php-module?
Do you have the latest version of PhpVersionSwitcher?
How does your config look like?

**Comment by krausv** [comment]
Thank you for response.

Yes, i read the 3rd point and i have the latest version of PhpVersionSwitcher (1.5.0).

~~~
{
	"phpDir": "C:\\xampp\\php",
	"services": [
		//{
			//"label": "Apache 2.4",
			//"name": "Apache2.4"
		//},
		//{
			//"label": "MySQL 5.6",
			//"name": "MySQL"
		//}
	],
	"executables": [
		 {
		 	"label": "Apache 2.4",
		 	"path": "C:\\xampp\\apache\\bin\\httpd.exe"
		 },
		 {
			"label": "MySQL 5.6",
			"path": "C:\\xampp\\mysql\\bin\\mysqld.exe"
		 },
		// {
		// 	"label": "PHP FastCGI",
		// 	"path": "C:\\web\\php\\active\\php-cgi.exe",
		// 	"multiple": [
		// 		{"args": "-b 127.0.0.1:9300", "label": "PHP FastCGI (9300)"},
		// 		{"args": "-b 127.0.0.1:9301", "label": "PHP FastCGI (9301)"},
		// 		{"args": "-b 127.0.0.1:9302", "label": "PHP FastCGI (9302)"},
		// 		{"args": "-b 127.0.0.1:9303", "label": "PHP FastCGI (9303)"},
		// 		{"args": "-b 127.0.0.1:9304", "label": "PHP FastCGI (9304)"},
		// 		{"args": "-b 127.0.0.1:9305", "label": "PHP FastCGI (9305)"},
		// 		{"args": "-b 127.0.0.1:9306", "label": "PHP FastCGI (9306)"},
		// 		{"args": "-b 127.0.0.1:9307", "label": "PHP FastCGI (9307)"},
		// 		{"args": "-b 127.0.0.1:9308", "label": "PHP FastCGI (9308)"},
		// 		{"args": "-b 127.0.0.1:9309", "label": "PHP FastCGI (9309)"}
		// 	]
		// },
		// {
		// 	"label": "PHP built-in server",
		// 	"path": "C:\\web\\php\\active\\php.exe",
		// 	"args": "-S 127.0.0.1:9990 -t C:\\projects"
		// }
	]
}
~~~

and apache conf

~~~
#
# PHP-Module setup
#
LoadFile "C:/xampp/php/active/php${PHP_VERSION_MAJOR}ts.dll"
LoadModule php${PHP_VERSION_MAJOR}_module "C:/xampp/php/active/php${PHP_VERSION_MAJOR}apache2_4.dll"
~~~

**Comment by JanTvrdik** [comment]
* Did you download TS version of PHP7?
* Is there anything in Windows Event Viewer ("Prohlížeč událostí" in Czech) – Windows Logs – Application?
* Does choosing Retry ("Opakovat" in Czech) help?

> If I switch php version and start apache from cmd, so apache works correctly

How do you start Apache from cmd?
