### ISSUE TITLE
Content of active configuration file is doubled

### ISSUE THREAD

**Issue by BigCharlie** [JanTvrdik/PhpVersionSwitcher#24]
I met a bug in v1.6.0 beta - when switched to specific PHP version, content of php.ini in "active" directory is doubled.

Same configuration in v1.5.0 works perfectly.

My setup:
I edited phpDir in PhpVersionSwitcher.json, nothing else.

3 PHP directories, 3 config files
5.6.6 => 5.6.6.ini
5.6.19 => 5.6.19.ini
7.0.4 => 7.0.4.ini

**Comment by JanTvrdik** [comment]
I think I known where the bug is. Let me check.
